export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER',
};

export const USER_STATUSES = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  SOFT_DELETED: 'SOFT_DELETED',
};

export const ADMIN_INVITE_STATUSES = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

export const IDENTITY_LOCK_STATUSES = {
  LOCKED: 'LOCKED',
  RELEASED: 'RELEASED',
};

export const IDENTITY_TYPES = {
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
};

export const IDENTITY_LOCK_REASONS = {
  ACTIVE_ACCOUNT: 'ACTIVE_ACCOUNT',
  ADMIN_INVITE: 'ADMIN_INVITE',
  ADMIN_INVITE_CANCELLED: 'ADMIN_INVITE_CANCELLED',
  BLOCKED_ACCOUNT: 'BLOCKED_ACCOUNT',
  DELETED_ACCOUNT: 'DELETED_ACCOUNT',
  MANUALLY_RELEASED: 'MANUALLY_RELEASED',
  ROOT_SUPER_ADMIN: 'ROOT_SUPER_ADMIN',
};

export const ALL_APP_ROLES = Object.values(USER_ROLES);

export const ADMIN_ROLES = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN,
];

export const ACTIVE_QUIZ_STATUSES = ['ACTIVE'];
